### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by JustLuuuu** [helikon-labs/followthedot#137]
I added an address in the search, but after clicking enter, nothing happened. 😭 

I tried to refresh the other address, but nothing. I use chrome.

https://github.com/user-attachments/assets/7f99117b-10b4-44e7-abae-3f273e4a4cf7

**Comment by kukabi** [comment]
Hey @JustLuuuu, thanks for the notice! That usually means that either there has been no balance transfers from/to the account (likely in your case, if it's not a bug), or the account doesn't exist on Polkadot. followthedot only stores the accounts with at least 1 balance transfer in either direction.

Could you please try to visit:

https://polkadot.subscan.io/account/{address_here}?tab=transfer

and see if there has been any transfers to/from the account? If so, please let me know so I can look into it.

**Comment by JustLuuuu** [comment]
Hey @kukabi I just figured it out. I was using a generic address, not the Polkadot one. 😅

**Comment by kukabi** [comment]
@JustLuuuu ok that's a bug, it should convert, thanks. 😄
